apiVersion: v1
kind: Service

metadata:
  name: sdxl-base
  namespace: sadeem

spec:
  selector:
    app: sdxl-base

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: ClusterIP