apiVersion: apps/v1
kind: Deployment

metadata:
  name: sdxl-base
  namespace: sadeem
  labels:
    app: sdxl-base

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sdxl-base

  template:
    metadata:
      labels:
        app: sdxl-base

    spec:
      containers:
        - name: sdxl-base
          image: sadeemalboqami/sdxl-vllm:phase3

          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: token

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "4"
              memory: "12Gi"
              nvidia.com/gpu: 1

            limits:
              cpu: "8"
              memory: "24Gi"
              nvidia.com/gpu: 1

          volumeMounts:
            - name: hf-cache
              mountPath: /root/.cache/huggingface

      volumes:
        - name: hf-cache
          hostPath:
            path: /var/lib/hf-cache
            type: Directory